### ISSUE TITLE
Evaluation failed: RangeError: Maximum call stack size exceeded in isElementWidget.js

### ISSUE THREAD

**Issue by geirsf** [qualweb/core#10]
The evaluation failed with: RangeError: Maximum call stack size exceeded in isElementWidget.js 

**Version of QualWeb Core:** 0.4.19
**Site tested:** https://www.nav.no/soknader/nb/person

Error: Evaluation failed: RangeError: Maximum call stack size exceeded
    at Object.isElementWidget [as default] (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/isElementWidget.js?:6:16)
    at getAccessibleNameFromAriaLabelledBy (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:171:45)
    at getAccessibleNameRecursion (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:46:17)
    at getAccessibleNameFromAriaLabelledBy (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:177:32)
    at getAccessibleNameRecursion (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:46:17)
    at getAccessibleNameFromAriaLabelledBy (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:177:32)
    at getAccessibleNameRecursion (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:46:17)
    at getAccessibleNameFromAriaLabelledBy (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:177:32)
    at getAccessibleNameRecursion (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:46:17)
    at getAccessibleNameFromAriaLabelledBy (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:177:32)
    at ExecutionContext._evaluateInternal (Qualweb-server\Qualweb-server\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (Qualweb-server\Qualweb-server\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async Evaluation.executeACT (Qualweb-server\Qualweb-server\node_modules\@qualweb\evaluation\dist\index.js:87:27)
    at async Evaluation.evaluatePage (\Qualweb-server\Qualweb-server\node_modules\@qualweb\evaluation\dist\index.js:162:57)
    at async System.runModules (Qualweb-server\Qualweb-server\node_modules\@qualweb\core\dist\system.js:113:42)
    at async Promise.all (index 0)
    at async System.execute (Qualweb-server\Qualweb-server\node_modules\@qualweb\core\dist\system.js:88:13)
    at async evaluate (Qualweb-server\Qualweb-server\node_modules\@qualweb\core\dist\index.js:19:5)
    at async test_side (Qualweb-server\Qualweb-server\tester.js:174:29)

**Comment by carlosapaduarte** [comment]
Hi @geirsf 
It's been fixed. Please update to the last version!

**Comment by geirsf** [comment]
@carlosapaduarte  Working great now!
