### ISSUE TITLE
Cannot find module qw-page

### ISSUE THREAD

**Issue by jrpool** [qualweb/core#33]
Recently `qualweb.evaluate()` is always failing with the error message “Cannot find module `qw-page`”. Installing `qw-page` then results in an error message ”Cannot find module `util`”. Installing `util` then results in an error message

```
puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:72
            this._reject(callback, new Errors_js_1.TargetCloseError('Target closed'));
```

The original error has this require stack:

```
Error: Cannot find module '@qualweb/qw-page'
Require stack:
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/QualwebPage.object.js
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/index.js
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/qualweb.js
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/index.js
- /Users/c162712/Documents/repos/poolcvs/testaro/tests/qualWeb.js
- /Users/c162712/Documents/repos/poolcvs/testaro/procs/doTestAct.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at QualwebPage.addNecessaryScripts (/Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/QualwebPage.object.js:76:27)
    at QualwebPage.getTestingData (/Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/QualwebPage.object.js:71:14)
    at async EvaluationManager.evaluate (/Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/EvaluationManager.object.js:12:29)
    at async /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/qualweb.js:65:44 {
  code: 'MODULE_NOT_FOUND',
```

`evaluate` is being called on line 136 at `https://github.com/cvs-health/testaro/blob/qwfix/tests/qualWeb.js`.

**Comment by carlosapaduarte** [comment]
Hi @jrpool 

QualWeb has had a minor update. You probably updated it and now need to change the way you use it. Please read the README.md in https://github.com/qualweb/qualweb/tree/main/packages/core

**Comment by jrpool** [comment]
Hi, @carlosapaduarte. Thank you for your reply. I thought I was following the README, but I shall look again.

**Comment by carlosapaduarte** [comment]
Make sure you removed from the dependencies any of the packages that have been deprecated (most likely @qualweb/types)

**Comment by jrpool** [comment]
After studying the README and trying to ensure conformity to it, I am still getting:

```
Error: Cannot find module '@qualweb/qw-page'
Require stack:
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/QualwebPage.object.js
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/index.js
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/qualweb.js
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/index.js
```

**Comment by jrpool** [comment]
I believe I am implementing the README, but still getting:

```
Error: Cannot find module '@qualweb/qw-page'
Require stack:
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/QualwebPage.object.js
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/index.js
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/qualweb.js
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/index.js
- /Users/c162712/Documents/repos/poolcvs/testaro/tests/qualWeb.js
- /Users/c162712/Documents/repos/poolcvs/testaro/procs/doTestAct.js
```

**Comment by Tellus** [comment]
This may be related to a hoisting issue due to missing dependencies in core. It was affecting projects managed by PNPM but not NPM as far as I could tell.
There's a fix for this in the develop branch but has not been pushed to main, yet.

Are you able to try out the develop version instead to see if it alleviates the issue? Should currently be version "0.0.0-develop-20241217135157".

**Comment by jrpool** [comment]
The develop version does not throw this error.

**Comment by Tellus** [comment]
Thank you for the fast turnaround!

I'll see if we can't get a quick main release out with the fix. If you need to run something ASAP you should be fine with the develop version - the only difference with main is this fix.
