### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by geirsf** [qualweb/core#5]
Page tested: https://www.dagbladet.no/pluss

Qualweb Core result:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Evaluation.executeHTML (Qualweb-server\Qualweb-server\node_modules\@qualweb\evaluation\dist\index.js:142:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Evaluation.evaluatePage (Qualweb-server\Qualweb-server\node_modules\@qualweb\evaluation\dist\index.js:181:63)
    at async System.runModules (Qualweb-server\Qualweb-server\node_modules\@qualweb\core\dist\system.js:113:42)
    at async Promise.all (index 0)
    at async System.execute (Qualweb-server\Qualweb-server\node_modules\@qualweb\core\dist\system.js:88:13)
    at async evaluate (Qualweb-server\node_modules\@qualweb\core\dist\index.js:19:5)
    at async Qualweb-server\Qualweb-server\server.js:142:25
(node:18440) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'modules' of undefined
    at Qualweb-server\Qualweb-server\server.js:145:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by joao-vicente** [comment]
Hi, this should be no longer an issue in the latest version (0.4.19). Can you test and give us some feedback?

**Comment by geirsf** [comment]
Great!   Will test again!

**Comment by geirsf** [comment]
Seems to work fine now!
