### ISSUE TITLE
Evaluation failed: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by geirsf** [qualweb/core#6]
Page tested:  https://www.sas.no/fly-med-oss/gruppereiser/

Qualweb Core result:
Error: Evaluation failed: RangeError: Maximum call stack size exceeded
    at QWElement.getElementSelector (webpack://QWPage/./node_modules/@qualweb/qw-element/dist/index.js?:200:23)
    at getElementRoleAName (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getElementRoleAName.js?:9:30)
    at Object.isElementWidget [as default] (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/isElementWidget.js?:6:16)
    at getAccessibleNameFromAriaLabelledBy (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:174:45)
    at getAccessibleNameRecursion (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:47:17)
    at getAccessibleNameFromAriaLabelledBy (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:180:32)
    at getAccessibleNameRecursion (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:47:17)
    at getAccessibleNameFromAriaLabelledBy (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:180:32)
    at getAccessibleNameRecursion (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:47:17)
    at getAccessibleNameFromAriaLabelledBy (webpack://ACTRules/./node_modules/@qualweb/util/dist/accessibilityUtils/getAccessibleName.js?:180:32)
    at ExecutionContext._evaluateInternal (Qualweb-server\Qualweb-server\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (Qualweb-server\Qualweb-server\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async Evaluation.executeACT (Qualweb-server\Qualweb-server\node_modules\@qualweb\evaluation\dist\index.js:88:27)
    at async Evaluation.evaluatePage (Qualweb-server\Qualweb-server\node_modules\@qualweb\evaluation\dist\index.js:178:57)
    at async System.runModules (Qualweb-server\Qualweb-server\node_modules\@qualweb\core\dist\system.js:113:42)
    at async Promise.all (index 0)
    at async System.execute (Qualweb-server\Qualweb-server\node_modules\@qualweb\core\dist\system.js:88:13)
    at async evaluate (Qualweb-server\Qualweb-server\node_modules\@qualweb\core\dist\index.js:19:5)
    at async Qualweb-server\Qualweb-server\server.js:153:25
(node:25548) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'modules' of undefined
    at Qualweb-server\Qualweb-server\server.js:156:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by joao-vicente** [comment]
Hi, this should be no longer an issue in the latest version (0.4.19). Can you test and give us some feedback?

**Comment by geirsf** [comment]
Tested again.  Seems to work fine now!
