### ISSUE TITLE
Error in QW_ACT_R4?

### ISSUE THREAD

**Issue by geirsf** [qualweb/core#7]
There seems to be an error in QW_ACT_R4.  It's trying to 'trim" an undefined object. 

Pages tested: https://www.dn.no/etterBors/

Qualweb result:
Error: Evaluation failed: TypeError: Cannot read property 'trim' of undefined
    at QW_ACT_R4.execute (webpack://ACTRules/./dist/rules/QW-ACT-R4.js?:107:57)
    at QW_ACT_R4.ElementExists.descriptor.value (webpack://ACTRules/./dist/lib/decorator.js?:34:27)
    at ACTRules.executeNotMappedRules (webpack://ACTRules/./dist/index.js?:144:45)
    at ACTRules.execute (webpack://ACTRules/./dist/index.js?:227:14)
    at __puppeteer_evaluation_script__:3:24
    at ExecutionContext._evaluateInternal (Qualweb-server\Qualweb-server\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (Qualweb-server\Qualweb-server\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async Evaluation.executeACT (Qualweb-server\Qualweb-server\node_modules\@qualweb\evaluation\dist\index.js:88:27)
    at async Evaluation.evaluatePage (Qualweb-server\Qualweb-server\node_modules\@qualweb\evaluation\dist\index.js:178:57)
    at async System.runModules (Qualweb-server\Qualweb-server\node_modules\@qualweb\core\dist\system.js:113:42)
    at async Promise.all (index 0)
    at async System.execute (Qualweb-server\Qualweb-server\node_modules\@qualweb\core\dist\system.js:88:13)
    at async evaluate (Qualweb-server\Qualweb-server\node_modules\@qualweb\core\dist\index.js:19:5)
    at async Qualweb-server\Qualweb-server\server.js:153:25
(node:7232) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'modules' of undefined
    at Qualweb-server\Qualweb-server\server.js:156:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by joao-vicente** [comment]
Hi, this should be no longer an issue in the latest version (0.4.19). Can you test and give us some feedback?

**Comment by geirsf** [comment]
Tested again, and now working fine in 0.4.19.
